"""
Django settings for ExcelImport project.

Generated by 'django-admin startproject' using Django 1.11.16.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'im5b2wd6imkb7*@f(miuayj=9&u-!!zvbtlx#z#c&^)pahrxke'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'excel_import.apps.ExcelImpoortConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ExcelImport.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ExcelImport.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'excel_django',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'ROOT',
        'PASSWORD': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

#######################配置文件#####################

EXCEL_EXPORT_PATH = "C:/"  # excel导出的路径

HEADER_LINE = 2  # excel表 表头从第几行开始,以excel行数为标准
START_LINE = 3  # excel表 有效数据从第几行开始,以excel行数为标准

SHEET_BLACKLIST = ['环比数据表', ]  # 不导入的表

# Sheet名 与 Model名 Form表单名的对应关系
# {'sheet名':[Model名, Form名]}
SHEET_TO_TABLE = {
    '站点信息表': ['BxStationDetail', 'BxStationDetailForm'],
    '直播配置': ['BxLiveUrl', 'BxLiveUrlForm'],
    '车型热度表': ['BxRoiTraffic', 'BxRoiTrafficForm'],
    '站点设备信息表': ['BxDevice', 'BxDeviceForm'],
    '竞品关联表': ['BxContrast', 'BxContrastForm'],
    '站点数据表': ['BxEverydayData', 'BxEverydayDataForm'],
    '环比数据表': ['BxEverydayContrastData', 'BxEverydayContrastDataForm'],
    '文本': ['BxText', 'BxTextForm'],
    '演艺时间': ['BxPerformArrange', 'BxPerformArrangeForm'],
}

# 各个表的唯一字段对应(多个字段联合唯一)
UNIQUE = {
    'BxStationDetail': ['station_id'],
    'BxLiveUrl': ['station_id', ],
    'BxRoiTraffic': ['station_id', 'roi_id', 'date'],
    'BxDevice': ['station_id', 'device_id'],
    'BxContrast': ['station_id', 'contrast_id'],
    'BxEverydayData': ['station_id', 'date'],
    # 'BxEverydayContrastData': ['parent_id', ],
    'BxText': ['brand_id', 'dashboard_id', ],
    'BxPerformArrange': ['station_id', 'station_name', 'start_time', 'end_time'],
}
